name = "qntm-dropbox"
main = "src/index.ts"
compatibility_date = "2024-02-08"

routes = [
  { pattern = "inbox.qntm.corpo.llc", custom_domain = true }
]

[[kv_namespaces]]
binding = "QNTM_KV"
id = "3a542ff3af7c466aba9cb401bc8a07e1"

[vars]
ENVELOPE_TTL_SECONDS = "604800"   # 7 days
MAX_ENVELOPE_SIZE = "65536"       # 64KB
MAX_MESSAGES_PER_CHANNEL = "512"
RATE_LIMIT_PER_MIN = "100"
